services:
  db:
    image: postgres:16-alpine
    container_name: appburovalie-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: appburovalie
      POSTGRES_USER: appburovalie
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change-moi-vite}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet

  api:
    build:
      context: ./backend
    container_name: appburovalie-api
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://appburovalie:${POSTGRES_PASSWORD:-change-moi-vite}@db:5432/appburovalie?schema=public
      JWT_SECRET: ${JWT_SECRET:-change-moi-avec-une-longue-phrase-secrete}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - appnet
    depends_on:
      - db

  adminer:
    image: adminer:latest
    container_name: appburovalie-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - appnet
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  appnet:
